version: '2'
services:
  tc-informix:
    image: "appiriodevops/informix:1.2"
    ports:
      - "2021:2021"
  tc-direct-build:
    image: "appiriodevops/direct-app:build"
    volumes:
      - "${DIRECT_APP_SRC_ROOT}:/root/direct"
      - "${BUILT_DATA}:/data"
  tc-direct-with-volume:
    image: "appiriodevops/direct-app:run-volume"
    links:
      - "tc-informix"
    hostname: cockpit.cloud.topcoder.com
    volumes:
      - "${BUILT_JBOSS_DIR}:/root/jboss-4.2.3.GA"
    ports:
      - "443:443"
      - "8180:8180"
      - "1198:1198"
      - "1199:1199"
      - "3973:3973"
      - "5446:5446"
  tc-direct:
    image: "appiriodevops/direct-app:run"
    links:
      - "tc-informix"
    hostname: cockpit.cloud.topcoder.com
    ports:
      - "443:443"
      - "8180:8180"
      - "1198:1198"
      - "1199:1199"
      - "3973:3973"
      - "5446:5446"
